env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: "ENCRYPTED[164b43f55300075a28b1ac43fcecc76b7a04fb82bfb2c4d8a154661cd0741583e714263a9ff7779a9eec5adcb2f79413]"

task:
    name: LineageOS
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 32G
    download_ccache_background_script:
      - set -evx
      - command=$(head /tmp/ci/ccache.sh -n $(expr $(grep upload /tmp/ci/ccache.sh -n | cut -f1 -d:) - 1))
      - bash -c "$command"
    sync_script:
      - set -evx
      - command=$(head /tmp/ci/build.sh -n $(expr $(grep "# build" /tmp/ci/build.sh -n | cut -f1 -d:) - 1))
      - bash -c "$command"
    monitor_background_script:
      - set -evx
      - command=$(tail /tmp/ci/ccache.sh -n +$(expr $(grep "# monitor" /tmp/ci/ccache.sh -n | cut -d : -f1) + 0) | head -n 13)
      - bash -c "$command"
    build_script:
      - set -evx
      - command=$(tail /tmp/ci/build.sh -n +$(expr $(grep "# build" /tmp/ci/build.sh -n | cut -f1 -d:) + 2) | head -n -16)
      - bash -c "$command"
    upload_rom_script:
      - set -evx
      - command=$(tail /tmp/ci/build.sh -n +$(expr $(grep "# upload" /tmp/ci/build.sh -n | cut -f1 -d:) + 2))
      - bash -c "$command"
    upload_ccache_script:
      - set -evx
      - command=$(tail /tmp/ci/ccache.sh -n +$(expr $(grep "# upload" /tmp/ci/ccache.sh -n | cut -f1 -d:) + 2))
      - bash -c "$command"
