env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_config: ""

task:
    name: DotOS
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 32G
    download_ccache_background_script:
      - set -vx
      - command=$(head CIRRUS_WORKING_DIR/ccache.sh -n $(expr $(grep upload CIRRUS_WORKING_DIR/ccache.sh -n | cut -f1 -d:) - 1))
      - bash -c "$command"
    sync_script:
      - set -vx
      - command=$(head CIRRUS_WORKING_DIR/build.sh -n $(expr $(grep "# build" CIRRUS_WORKING_DIR/build.sh -n | cut -f1 -d:) - 1))
      - bash -c "$command"
    monitor_background_script:
      - ./monitor
    build_script:
      - set -vx
      - command=$(tail CIRRUS_WORKING_DIR/build.sh -n +$(expr $(grep "# build" CIRRUS_WORKING_DIR/build.sh -n | cut -f1 -d:) + 2) | head -n -16)
      - bash -c "$command"
    upload_rom_script:
      - set -vx
      - command=$(tail CIRRUS_WORKING_DIR/build.sh -n +$(expr $(grep "# upload" CIRRUS_WORKING_DIR/build.sh -n | cut -f1 -d:) + 2))
      - bash -c "$command"
    upload_ccache_script:
      - set -vx
      - command=$(tail CIRRUS_WORKING_DIR/ccache.sh -n +$(expr $(grep "# upload" CIRRUS_WORKING_DIR/ccache.sh -n | cut -f1 -d:) + 2))
      - bash -c "$command"
